jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Install Expo CLI
      run: npm install -g expo-cli
    - name: Login to Expo
      run: expo whoami
      env:
        EXPO_TOKEN: ${{ secrets.EAS_TOKEN }}
    - name: Build Project with Expo
      run: expo build:android --non-interactive
      env:
        EXPO_TOKEN: ${{ secrets.EAS_TOKEN }}
