name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install Dependencies
        run: npm install && npm install -g eas-cli

      - name: Set Expo CLI token
        run: echo "export EXPO_CLI_TOKEN=${{ secrets.EXPO_CLI_TOKEN }}" >> $GITHUB_ENV
      - name: Login to Expo with EAS
        run: npx eas-cli login

      - name: Build with Fastlane 
        run: |
          cd fastlane
          fastlane build 

      
        
